### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by zfk513** [jeayu/bilibili-quickdo#1]
您好，想问下在技术有没有可能实现 像YouTube一样快捷键左右键快进10s/后退10s

**Comment by jeayu** [comment]
@zfk513 你好，试试
h5Player.currentTime += 10;
h5Player.currentTime -= 10;

**Comment by zfk513** [comment]
请问大概要加在哪 pause的原理是点击实现的吖 这个没法点击

**Comment by jeayu** [comment]
@zfk513 config.quickDo里配置一下，然后在keyHandler方法里处理一下，代码不难理解吧

**Comment by zfk513** [comment]
感谢 
前端小白成功了

**Comment by zfk513** [comment]
不过再想问下大佬 这个是有API参考的吗  
我之前没找到……
