### ISSUE TITLE
b站H5播放器更新，现在自带快捷键，一部分和脚本有冲突

### ISSUE THREAD

**Issue by nukewarrior** [jeayu/bilibili-quickdo#17]
![image](https://user-images.githubusercontent.com/10683831/133270687-d2c72849-3a34-4732-8576-d12190e8754c.png)
其中部分快捷键和脚本的冲突，是否可以考虑更新一下屏蔽b站自带的快捷键，尤其那几个投币点赞一键三连的快捷键，谢谢

**Comment by Satomi2333** [comment]
在大概这个位置修改一下脚本就可以了
                defaultShortCutCheckbox: {
                    options: {
                        f: { text: 'f键', status: OFF, bindKey: 'f' },
                        leftSquareBracket: { text: '[键', status: OFF, bindKey: '[' },
                        rightSquareBracket: { text: ']键', status: OFF, bindKey: ']' },
                        enter: { text: '回车键', status: OFF, bindKey: 'enter' },
                        up: { text: '↑键', status: OFF, bindKey: 'up' },
                        down: { text: '↓键', status: OFF, bindKey: 'down' },
                        right: { text: '←键', status: OFF, bindKey: 'left' },
                        left: { text: '→键', status: OFF, bindKey: 'right' },
                        space: { text: '空格键', status: OFF, bindKey: 'space' },
                        **q: { text: 'q键-点赞', status: OFF, bindKey: 'q' },
                        w: { text: 'w键-投币', status: OFF, bindKey: 'w' },
                        e: { text: 'e键-收藏', status: OFF, bindKey: 'e' },
                        r: { text: 'r键-长按三连', status: OFF, bindKey: 'r' },
                        d: { text: 'd键-关闭弹幕', status: OFF, bindKey: 'd' },
                        m: { text: 'm键-静音', status: OFF, bindKey: 'm' },**
                    },
                    btn: '屏蔽默认快捷键',
                },

**Comment by nukewarrior** [comment]
> 在大概这个位置修改一下脚本就可以了 defaultShortCutCheckbox: { options: { f: { text: 'f键', status: OFF, bindKey: 'f' }, leftSquareBracket: { text: '[键', status: OFF, bindKey: '[' }, rightSquareBracket: { text: ']键', status: OFF, bindKey: ']' }, enter: { text: '回车键', status: OFF, bindKey: 'enter' }, up: { text: '↑键', status: OFF, bindKey: 'up' }, down: { text: '↓键', status: OFF, bindKey: 'down' }, right: { text: '←键', status: OFF, bindKey: 'left' }, left: { text: '→键', status: OFF, bindKey: 'right' }, space: { text: '空格键', status: OFF, bindKey: 'space' }, **q: { text: 'q键-点赞', status: OFF, bindKey: 'q' }, w: { text: 'w键-投币', status: OFF, bindKey: 'w' }, e: { text: 'e键-收藏', status: OFF, bindKey: 'e' }, r: { text: 'r键-长按三连', status: OFF, bindKey: 'r' }, d: { text: 'd键-关闭弹幕', status: OFF, bindKey: 'd' }, m: { text: 'm键-静音', status: OFF, bindKey: 'm' },** }, btn: '屏蔽默认快捷键', },

好用，感谢！！！
