### ISSUE TITLE
更新最新版本后不显示设置界面

### ISSUE THREAD

**Issue by nukewarrior** [jeayu/bilibili-quickdo#19]
![image](https://user-images.githubusercontent.com/10683831/178416904-e02467ea-4802-49ad-bc7b-5a61478e84cc.png)

**Comment by jeayu** [comment]
` 键打开设置，不再依赖设置按钮了

**Comment by nukewarrior** [comment]
> 

我尝试了切换中英输入法，重启Chrome浏览器，禁用除了tampermonkey外的所有扩展，都按不出来设置面板😭
