### ISSUE TITLE
自动宽屏好像失效了，还希望能加入调整播放器大小的功能

### ISSUE THREAD

**Issue by ghost** [jeayu/bilibili-quickdo#2]

**Comment by jeayu** [comment]
@15899812958zqr 
b站新版又抽风了，可能过几天又好了。
如果比较急可以把255行的
`player.mode(WIDESCREEN);` 
改成 
`setTimeout(() => player.mode(WIDESCREEN), 200);`

像调整播放器大小这类个性化比较强的功能可能不会加上，本身不想搞得太复杂，基本上就是官方有的功能才做快捷操作支持
