### ISSUE TITLE
按`键无法打开设置面板

### ISSUE THREAD

**Issue by nukewarrior** [jeayu/bilibili-quickdo#20]
反复多次测试，发现可能和b站HTML5播放器版本有关？

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/10683831/178639330-fbb60a94-0fe7-4c1e-94f1-b7ac8ca4984d.png">
隐身模式下，3.13.12版本播放器能正常按出设置面板

<img width="531" alt="image" src="https://user-images.githubusercontent.com/10683831/178639426-a48aba6f-72d9-4e8d-8d50-43dc4981a4c7.png">
正常模式下2.81.11无法按出设置面板

**Comment by nukewarrior** [comment]
> 

隐身模式下登录账号后，播放器版本就变成了2.81.11，此时也发现按不出设置面板了

**Comment by jeayu** [comment]
不兼容2.x版本

**Comment by nukewarrior** [comment]
> 不兼容2.x版本

我找了半天没找到切换b站播放器的入口，网上也没搜到😂
大佬知道怎么切换么
