### ISSUE TITLE
感谢辛苦制作脚本 请问可否增加画质锁定功能

### ISSUE THREAD

**Issue by suheandzl** [jeayu/bilibili-quickdo#3]
首先先感谢辛苦制作脚本 非常好用！
想请问一下以后是否可以增加一下画质锁定的功能 现在B站的视频我这里一打开画质就被调成了自动
想锁定最高画质 请作者大大考虑

**Comment by jeayu** [comment]
@suheandzl 在autoHandler函数后面添加:
```
$('.bilibili-player-video-quality-menu').mouseover().mouseout();
$('.bui-select-item').filter((i, x) => !$(x).find('.bilibili-player-bigvip')[0]).eq(0).click();
$('.bpui-selectmenu-list-row').filter((i, x) => !$(x).find('.bilibili-player-bigvip')[0]).eq(0).click();
```
如果是大会员的话去掉`.filter((i, x) => !$(x).find('.bilibili-player-bigvip')[0])`

**Comment by suheandzl** [comment]
不好意思 我不太懂这个。。。求赐教

**Comment by jeayu** [comment]
@suheandzl 进入管理面板,点击编辑可以编辑脚本,找到autoHandler函数(238行),在函数里粘贴上面三行代码,crtl+s保存

**Comment by suheandzl** [comment]
哇！成功了！非常感谢大大的详细讲解！
请问一下大大这个功能会正式加入到脚本中吗？真的很方便！

**Comment by suheandzl** [comment]
看到了大大的更新 非常感谢〜！
